2023-12-11 13:54:23 jdbc[3]: exception
com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLSyntaxErrorException: (Message 42S02 not found); SQL statement:
SELECT 1 FROM ultimatestacker_migrations [42102-200]
2023-12-11 22:18:02 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1527)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1360)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2023-12-11 22:18:02 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1527)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1360)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2023-12-11 22:18:03 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1527)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1360)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2023-12-11 22:18:03 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1527)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1360)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2023-12-11 22:18:03 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1527)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1360)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2023-12-14 11:09:28 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1527)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1360)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2023-12-14 11:09:28 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1527)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1360)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2023-12-14 11:09:28 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1527)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1360)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2023-12-14 11:09:28 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1527)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1360)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2023-12-14 11:09:28 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1527)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1360)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2023-12-14 11:09:28 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1527)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1360)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2023-12-14 18:10:58 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1527)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1360)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2023-12-14 18:10:58 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1527)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1360)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2023-12-14 18:10:58 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1527)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1360)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2023-12-14 18:10:58 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1527)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1360)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2023-12-14 18:10:58 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1527)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1360)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2023-12-14 18:10:59 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1527)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1360)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2024-01-06 00:04:26 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2024-01-06 00:23:08 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2024-01-06 00:23:08 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2024-01-06 00:23:08 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2024-01-06 00:23:08 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2024-01-06 00:23:08 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2024-01-06 00:23:08 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2024-01-06 00:23:09 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2024-01-28 18:59:30 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2024-01-28 18:59:31 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2024-01-28 18:59:31 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2024-01-28 18:59:31 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2024-01-28 18:59:31 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2024-01-28 18:59:57 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2024-01-28 18:59:57 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2024-01-28 18:59:57 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2024-01-28 18:59:57 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2024-01-28 18:59:57 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2024-01-28 18:59:57 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
2024-01-28 18:59:57 database: flush
com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.craftaro.ultimatestacker.core.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.craftaro.ultimatestacker.core.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 32 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/media/aranthanachai/7FBA-7210/Server/SkyBlock 1.12.2/plugins/UltimateStacker/ultimatestacker.mv.db [1.4.200/7]
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 26 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at com.craftaro.ultimatestacker.core.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 27 more
